### ISSUE TITLE
Uses "cmd" keybindings on Windows/Linux

### ISSUE THREAD

**Issue by adamfaulkner** [joefitzgerald/navigator-godef#1]
Hi, thanks for working on this package. This currently uses "cmd" instead of "ctrl" for keybindings on Windows/Linux. This isn't consistent with what other packages do.

For example, autocomplete-python does this

```
'.platform-darwin atom-text-editor[data-grammar~=python]:not(.mini)':
  'alt-cmd-g': 'autocomplete-python:go-to-definition'

'.platform-linux atom-text-editor[data-grammar~=python]:not(.mini)':
  'ctrl-alt-g': 'autocomplete-python:go-to-definition'

'.platform-win32 atom-text-editor[data-grammar~=python]:not(.mini)':
  'ctrl-alt-g': 'autocomplete-python:go-to-definition'
```

Would you mind making this change?

**Comment by adamfaulkner** [comment]
I should add that I'm willing to send you a pull request, but I wanted to check if this is something you'd want to do before sending that out.

**Comment by joefitzgerald** [comment]
By all means, PRs welcomed!

**Comment by silasdavis** [comment]
Any chance of a patch release with this change?

**Comment by joefitzgerald** [comment]
Done. Sorry for missing that!
