### ISSUE TITLE
Switch godef to use guru

### ISSUE THREAD

**Issue by bobbytables** [joefitzgerald/navigator-godef#14]
See: [go-guru](https://godoc.org/golang.org/x/tools/cmd/guru)

**Comment by zamicol** [comment]
Related: https://github.com/fatih/vim-go/issues/277#issuecomment-215212947.  The godef maintainer recommends switching to go-guru.

**Comment by joefitzgerald** [comment]
This package is deprecated. Please ensure you are running the latest version of Atom and go-plus, and uninstall this package.

Additionally, this is also now an option in go-plus (to use guru).
