### ISSUE TITLE
Could not resolve 'navigator-godef' to a package path

### ISSUE THREAD

**Issue by integrii** [joefitzgerald/navigator-godef#26]
```
🏠  master eg@Erics-Air:~$ atom -v
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

macOS 10.12.2 Beta (16C32e)

Any ideas?

**Comment by zamicol** [comment]
I might be having a similar issue.  

```
navigator-go
godef returned invalid file path
parseLocalPackage error: no more package files found 
{my very valid path here}
```

I'm on Linux, Atom version 1.11.2

**Comment by integrii** [comment]
I see this error when I open the JavaScript console within atom. My navigator stopped working sometime after one of the Mac beta updates.  Does anyone have troubleshooting steps?

Where should the files be located?

**Comment by joefitzgerald** [comment]
This package is deprecated. Please ensure you are running the latest version of Atom and go-plus, and uninstall this package.
