### ISSUE TITLE
Scroll the definition to the center of the window

### ISSUE THREAD

**Issue by cristian-pirnog** [joefitzgerald/navigator-godef#27]
Hi,

first of all, thanks for writing the package! It's awesome, I use it all the time and it really makes me faster in my work.

I think a very useful addition to the functionality would be to bring the definition to the center of the window, after moving the cursor to it. What I currently see is that often the definition is at the bottom (i.e. the third last line) of the window and I have to scroll down in order to see the function's body.

Cheers,
Cristian

**Comment by lloiser** [comment]
This has been fixed a while ago in [`go-plus`](https://github.com/joefitzgerald/go-plus). Please update `go-plus` to the latest version 5.1.1

**Comment by cristian-pirnog** [comment]
Thanks! It works now. See issue #28 for reason why one can have outdated packages on Linux.
