### ISSUE TITLE
Check for existing target buffer in all panes

### ISSUE THREAD

**Issue by cristian-pirnog** [joefitzgerald/navigator-godef#28]
It would be nice if the package would check for the an open buffer for the file that contains the symbol definition (i.e. the **target buffer**) in all panes. Currently, if the **target buffer** is already opened in the same pane with the buffer where the goto-definition request was made, then it will be reused. However, if the **target buffer** is already opened in a different pane, a new buffer for the same file will be opened in the current pane.

**Comment by lloiser** [comment]
This has been fixed a while ago in [`go-plus`](https://github.com/joefitzgerald/go-plus). Please update `go-plus` to the latest version 5.1.1

**Comment by cristian-pirnog** [comment]
Thanks for the quick reply!
For future reference: the reason for the old version was that I use `atom` on Linux, where it doesn't auto-upgrade the editor. Consequently, it was showing `navigator-go v5.0.9` as the latest version. Only after manually upgrading `atom` was I able to upgrade to the latest version of `navigator-go`, `go-plus`, etc.
