### ISSUE TITLE
Error installing navigator-godef dependencies

### ISSUE THREAD

**Issue by ericychoi** [joefitzgerald/navigator-godef#29]
![image](https://cloud.githubusercontent.com/assets/6855306/25066943/563612ea-21e9-11e7-8e55-8ae692cb36f2.png)

I get this error on start up:
`go-config: Request for package information failed: Not Found`

Could you help me debug this?

**Comment by joefitzgerald** [comment]
navigator-go is deprecated. Please uninstall it, update to the latest version of Atom, and install go-plus.
