### ISSUE TITLE
failed to navigate to packages under vendor

### ISSUE THREAD

**Issue by zhouhaibing089** [joefitzgerald/navigator-godef#4]
Hi,

Really appreciated this awesome package.

Recently, I moved all my dependencies into `vendor` folder to in favor of the go1.6, but after that I can not use `Alt + Command + G` to find/jump to the definition.

Looking forward a fix!

Thanks.

**Comment by Taik** [comment]
Vim-go recently moved to using https://godoc.org/golang.org/x/tools/cmd/guru. Maybe it is worth taking a look at?

**Comment by yinshiua** [comment]
+1 Having the same issue

**Comment by darkstar238** [comment]
+1

**Comment by zmb3** [comment]
There are plans to move to guru, but `godef` does support vendor directories as of May.

See: https://github.com/rogpeppe/godef/pull/33

**Comment by zhouhaibing089** [comment]
@zmb3 it does not work for me.

**Comment by zhouhaibing089** [comment]
Yeah! It works, for those who did not catch this, please run:

``` console
$ go get github.com/rogpeppe/godef
```

to update this package.
