### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ghost** [joefitzgerald/navigator-godef#6]
I installed the plugin and found no way to see or jump to any definitions when placing the cursor inside a variable, imported package, etc.

**Comment by dkwasnick** [comment]
command+option+G

**Comment by ghost** [comment]
Thanks. Is this an Atom convention or did I miss this shortcut from somewhere?

**Comment by dkwasnick** [comment]
I'm not sure, I actually had the same question as you, but looking at one of the other open issues (#4) answered it. I wish you could right-click on the variable and click "jump to definition".
